### ISSUE TITLE
Self Patch menu

### ISSUE THREAD

**Issue by bithack3r** [n6333373/sublime-self-patcher#1]
I extracted the zip and copied the folder to PACKAGES folder, restarted the app but nothing shows up in the menu.

**Comment by bithack3r** [comment]
Fixed it by making sure it's copied only in  C:\Users\User\AppData\Roaming\Sublime Text\Packages

**Comment by sergeevabc** [comment]
Is it true that Sublime Merge can only be patched externally from running Sublime Text?

**Comment by n6333373** [comment]
> Is it true that Sublime Merge can only be patched externally from running Sublime Text?

What's your expectation? You can patch it even with a website but that's a non-goal here.

**Comment by sergeevabc** [comment]
> What's your expectation? 

Initially, I thought this patch should be unpacked to `SublimeMerge\Data\Packages\` like it is advised do with Sublime Text. But Sublime Merge does not use Python, that's why you see Patch action in the app's menu after unpacking, but it is grayed out. Fortunately, external patching from Sublime Text menu works as expected. So essentially you need Sublime Text to patch Sublime Merge, that's what I was missing.
